[operation]
wandb_flag = 1
wandb_model_freq = 100
operation = 'test'     # unet, gan, vae, diffusion - training + testing + inference
device = 'cuda'


[dataset]


[model]
model = 'gan'

[unet]

[gan]
name = 'simple_gan'
lr = 3e-4
z_dim = 64
image_dim = 784
batch_size = 4
num_epochs = 1

[gan.criterion]
name = 'bceloss'

[gan.gen]
[gan.gen.opt]
name = 'adam'
lr = 3e-4
[gan.disc]
[gan.disc.opt]
name = 'adam'
lr = 3e-4


[diffusion]

[vae]
